[project]
name = "pytorch-intro"
version = "0.1.0"
description = "Intro to working with PyTorch"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel",
    "ipynb",
    "ipython",
    "jupyter",
    "matplotlib",
    "numpy",
    "torch",
    "torchvision",
]
